// Generated by tools/fxtable.py --header (the sources of core/fx/fxmap.json).
// Parameter indices (address / 2) of each BMC effect, by effect ID.
#pragma once

namespace fxp {

// 1 Filter+Drive (CTRL 1-3: CUTOFF, RESONANCE, DRIVE)
namespace fx01 { enum { CUTOFF, RESONANCE, DRIVE, FLT_TYPE, LOW_FREQ, LOW_GAIN, LEVEL, COUNT }; }
// 2 TimeCtrlDly (CTRL 1-3: TIME, FEEDBACK, LEVEL)
namespace fx02 { enum { SYNC, LEVEL, TIME, FEEDBACK, HIGH_CUT, HIGH_DAMP, H_DAMP_F, LOW_DAMP, L_DAMP_F, COUNT }; }
// 3 Isolator (CTRL 1-3: LOW, MID, HIGH)
namespace fx03 { enum { BALANCE, LOW, MID, HIGH, COUNT }; }
// 4 Crusher (CTRL 1-3: FILTER, RATE, BALANCE)
namespace fx04 { enum { BALANCE, RATE, FILTER, COUNT }; }
// 5 Phaser (CTRL 1-3: DEPTH, RATE, MANUAL)
namespace fx05 { enum { BALANCE, RATE, DEPTH, RESONANCE, MANUAL, TYPE, SYNC, COUNT }; }
// 6 Flanger (CTRL 1-3: DEPTH, RATE, MANUAL)
namespace fx06 { enum { BALANCE, RATE, DEPTH, RESONANCE, MANUAL, LOW_CUT_F, MODE, SYNC, COUNT }; }
// 7 Overdrive (CTRL 1-3: DRIVE, TONE, BALANCE)
namespace fx07 { enum { BALANCE, DRIVE, TONE, LEVEL, COUNT }; }
// 8 Distortion (CTRL 1-3: DRIVE, TONE, BALANCE)
namespace fx08 { enum { BALANCE, DRIVE, TONE, LEVEL, COUNT }; }
// 9 Tape Echo (CTRL 1-3: TIME, FEEDBACK, LEVEL)
namespace fx09 { enum { SYNC, LEVEL, TIME, FEEDBACK, MODE, BASS, TREBLE, PAN_S, PAN_M, PAN_L, TAPE_DIST, W_F_RATE, W_F_DEPTH, COUNT }; }
// 10 Reverb (CTRL 1-3: TYPE, TIME, LEVEL)
namespace fx10 { enum { TYPE, TIME, LEVEL, PRE_DELAY, LOW_CUT, HIGH_CUT, DENSITY, COUNT }; }
// 11 WrmSaturator (CTRL 1-3: DRIVE, EQ LOW, EQ HIGH)
namespace fx11 { enum { LOW_FREQ, LOW_GAIN, HI_SLOPE, HI_FREQ, PRE1_TYPE, PRE1_FREQ, PRE1_GAIN, DRIVE, PST1_TYPE, PST1_FREQ, EQ_LOW, PST2_TYPE, PST2_FREQ, EQ_HIGH, PST3_TYPE, PST3_FREQ, PST3_GAIN, PST3_Q, SENSE, POST_GAIN, BALANCE, LEVEL, COUNT }; }
// 12 Resonator (CTRL 1-3: ROOT, BRIGHT, FEEDBACK)
namespace fx12 { enum { BALANCE, PANNING, LOW_CUT_F, ROOT, CHORD, FEEDBACK, BRIGHT, ENV_MOD, COUNT }; }
// 13 DJFX Looper (CTRL 1-3: LENGTH, SPEED, LOOP SW)
namespace fx13 { enum { LENGTH, SPEED, LOOP_SW, LEVEL, COUNT }; }
// 14 Chorus (CTRL 1-3: DEPTH, RATE, BALANCE)
namespace fx14 { enum { RATE, LEVEL, BALANCE, DEPTH, EQ_LOW, EQ_HIGH, COUNT }; }
// 15 JUNO Chorus (CTRL 1-3: MODE, NOISE, BALANCE)
namespace fx15 { enum { MODE, NOISE, BALANCE, LEVEL, COUNT }; }
// 16 Tremolo/Pan (CTRL 1-3: DEPTH, RATE, TYPE)
namespace fx16 { enum { TYPE, WAVE, SYNC, RATE, DEPTH, EQ_LOW, EQ_HIGH, LEVEL, PHASE, COUNT }; }
// 17 Wah (CTRL 1-3: PEAK, RATE, MANUAL)
namespace fx17 { enum { FLT_TYPE, MANUAL, PEAK, SYNC, RATE, BALANCE, DEPTH, EQ_LOW, EQ_HIGH, LEVEL, COUNT }; }
// 18 Sync Delay (CTRL 1-3: TIME, FEEDBACK, LEVEL)
namespace fx18 { enum { LEVEL, TIME, FEEDBACK, HIGH_CUT, HIGH_DAMP, H_DAMP_F, LOW_DAMP, L_DAMP_F, COUNT }; }
// 19 Equalizer (CTRL 1-3: LOW GAIN, MID GAIN, HIGH GAIN)
namespace fx19 { enum { LOW_FREQ, LOW_GAIN, MID_FREQ, MID_GAIN, MID_Q, MID2_FREQ, MID2_GAIN, MID2_Q, HIGH_FREQ, HIGH_GAIN, LEVEL, BALANCE, COUNT }; }
// 20 Lo-fi (CTRL 1-3: PRE FILT, LOFI TYPE, TONE)
namespace fx20 { enum { PRE_FILT, LOFI_TYPE, POST_FILT, CUTOFF, BALANCE, LEVEL, TONE, COUNT }; }
// 21 Ring Mod (CTRL 1-3: FREQUENCY, SENS, BALANCE)
namespace fx21 { enum { FREQUENCY, SENS, POLARITY, EQ_LOW, EQ_HIGH, BALANCE, LEVEL, COUNT }; }
// 22 Chromatic PS (CTRL 1-3: PITCH1, PITCH2, BALANCE)
namespace fx22 { enum { PITCH1, FINE1, PAN1, LEVEL1, PITCH2, FINE2, PAN2, LEVEL2, EQ_LOW, EQ_HIGH, BALANCE, LEVEL, COUNT }; }
// 23 Gt Amp Sim (CTRL 1-3: AMP TYPE, DRIVE, LEVEL)
namespace fx23 { enum { AMP_SW, AMP_TYPE, DRIVE, MASTER, GAIN, BASS, MIDDLE, TREBLE, PRESENCE, BRIGHT, SP_SW, SP_TYPE, MIC_SET, MIC_LEVEL, DIRECT, PAN, LEVEL, AMP_TYPE_2, COUNT }; }
// 24 Stopper (CTRL 1-3: DEPTH, RATE, RESONANCE)
namespace fx24 { enum { RATE, DEPTH, HOLD, FLT_MOD, RESONANCE, AMP_MOD, COUNT }; }
// 25 Downer (CTRL 1-3: DEPTH, RATE, FILTER)
namespace fx25 { enum { RATE, PITCH, DEPTH, FILTER, RESONANCE, COUNT }; }
// 26 Slicer (CTRL 1-3: PATTERN, SPEED, DEPTH)
namespace fx26 { enum { PATTERN, DEPTH, SPEED, SYNC, ATTACK, SHUFFLE, RESET_SW, RESET_THR, MODE, LEVEL, COUNT }; }
// 27 Auto Pitch (CTRL 1-3: PITCH, FORMANT, BALANCE)
namespace fx27 { enum { PITCH, FORMANT, BALANCE, AT_PITCH, KEY, ROBOT, COUNT }; }
// 28 Compressor (CTRL 1-3: SUSTAIN, ATTACK, RATIO)
namespace fx28 { enum { SUSTAIN, ATTACK, LEVEL, RATIO, MODE, COUNT }; }
// 29 COMPRESSOR 2 (CTRL 1-3: SUSTAIN, ATTACK, RATIO)
namespace fx29 { enum { SUSTAIN, ATTACK, LEVEL, RATIO, TONE, MODE, COUNT }; }
// 30 Scatter (CTRL 1-3: TYPE, DEPTH, SCATTER)
namespace fx30 { enum { TYPE, DEPTH, BALANCE, SCATTER, SPEED, COUNT }; }
// 31 404 VinylSim (CTRL 1-3: FREQUENCY, NOISE, WOW FLUT)
namespace fx31 { enum { FREQUENCY, NOISE, WOW_FLUT, DIST, DISC_TYPE, BALANCE, COUNT }; }
// 32 303 VinylSim (CTRL 1-3: COMP, NOISE, WOW FLUT)
namespace fx32 { enum { COMP, NOISE, WOW_FLUT, BALANCE, LEVEL, COUNT }; }
// 33 Zan-Zou (CTRL 1-3: TIME, FEEDBACK, HF DAMP)
namespace fx33 { enum { M_D_LEVEL, M_D_MODE, M_D_SYNC, M_D_TIME, M_D_FBK, M_HF_DAMP, M_D_PAN1, M_D_PAN2, M_D_PAN3, M_D_PAN4, LEVEL, MODE, SYNC, TIME, FEEDBACK, HF_DAMP, S_D_PAN1, S_D_PAN2, S_D_PAN3, S_D_PAN4, COUNT }; }
// 34 Super Filter (CTRL 1-3: CUTOFF, RESONANCE, FLT TYPE)
namespace fx34 { enum { FLT_TYPE, FLT_SLOPE, CUTOFF, RESONANCE, FLT_GAIN, MOD_SW, MOD_WAVE, SYNC, RATE, DEPTH, ATTACK, LEVEL, COUNT }; }
// 35 Hyper-Reso (CTRL 1-3: NOTE, SPREAD, CHARACTER)
namespace fx35 { enum { BALANCE, SCALE, LOW_CUT_F, NOTE, SPREAD, FEEDBACK, CHARACTER, ENV_MOD, COUNT }; }
// 36 Ko-Da-Ma (CTRL 1-3: TIME, FEEDBACK, SEND)
namespace fx36 { enum { LEVEL, TIME, FEEDBACK, MODE, TAP, HIGH_CUT, HIGH_DAMP, H_DAMP_F, LOW_DAMP, L_DAMP_F, SEND, COUNT }; }
// 37 Ha-Dou (CTRL 1-3: MOD DEPTH, TIME, LEVEL)
namespace fx37 { enum { MOD_DEPTH, TIME, LEVEL, PRE_DELAY, LOW_CUT, HIGH_CUT, DENSITY, COUNT }; }
// 38 To-Gu-Ro (CTRL 1-3: DEPTH, RATE, RESONANCE)
namespace fx38 { enum { RATE, DEPTH, HOLD, FLT_MOD, RESONANCE, AMP_MOD, SYNC, COUNT }; }
// 39 Cassette Sim (CTRL 1-3: TONE, HISS, AGE)
namespace fx39 { enum { HISS, AGE, TONE, DRIVE, WOW_FLUT, CATCH, BALANCE, COUNT }; }
// 40 SBF (CTRL 1-3: INTERVAL, WIDTH, BALANCE)
namespace fx40 { enum { BALANCE, INTERVAL, WIDTH, TYPE, GAIN, COUNT }; }
// 41 SX Delay (CTRL 1-3: TIME, FEEDBACK, BALANCE)
namespace fx41 { enum { SYNC, TIME, PHASE, FEEDBACK, FBK_ROUTE, HF_DAMP, MOD_SW, MOD_RATE, MOD_DEPTH, BALANCE, EQ_LOW, EQ_HIGH, LEVEL, COUNT }; }
// 42 Vocoder (CTRL 1-3: NOTE, FORMANT, TONE)
namespace fx42 { enum { NOTE, FORMANT, SCALE, CHORD, COLOR, TONE, LEVEL, BALANCE, COUNT }; }
// 43 Harmony (CTRL 1-3: PITCH, FORMANT, BALANCE)
namespace fx43 { enum { PITCH, FORMANT, BALANCE, AT_PITCH, KEY, HARMONY, COUNT }; }
// 44 SX Reverb (CTRL 1-3: TIME, TONE, BALANCE)
namespace fx44 { enum { TIME, TONE, BALANCE, TYPE, PRE_DELAY, LEVEL, COUNT }; }
// 45 Sub Sonic (CTRL 1-3: BALANCE)
namespace fx45 { enum { BALANCE, COUNT }; }
// 46 Back Spin (CTRL 1-3: LENGTH, SPEED, BACK SW)
namespace fx46 { enum { LENGTH, SPEED, BACK_SW, MODE, FLT_MOD, SYNC, RESONANCE, AMP_MOD, COUNT }; }
// 47 Cloud Delay (CTRL 1-3: WINDOW, PITCH, BALANCE)
namespace fx47 { enum { BALANCE, PITCH, WINDOW, FEEDBACK, CLOUDY, LOFI, COUNT }; }
// 48 DJFX Delay (CTRL 1-3: LENGTH, TIME, LOOP SW)
namespace fx48 { enum { LENGTH, TIME, LOOP_SW, FEEDBACK, LEVEL, SYNC, HIGH_CUT, HIGH_DAMP, H_DAMP_F, LOW_DAMP, L_DAMP_F, COUNT }; }

// Starting values of parameters the firmware may never send (by effect, index).
constexpr unsigned char kNeutral[49][32] = {
    {},
    {0, 0, 0, 0, 0, 0, 0}, // Filter+Drive
    {0, 0, 0, 0, 0, 0, 0, 0, 0}, // TimeCtrlDly
    {0, 0, 0, 0}, // Isolator
    {0, 0, 0}, // Crusher
    {0, 0, 0, 0, 0, 0, 0}, // Phaser
    {0, 0, 0, 0, 0, 0, 0, 0}, // Flanger
    {0, 0, 0, 0}, // Overdrive
    {0, 0, 0, 0}, // Distortion
    {0, 0, 0, 0, 0, 15, 15, 0, 0, 0, 0, 0, 0}, // Tape Echo
    {0, 0, 0, 0, 0, 0, 0}, // Reverb
    {0, 15, 0, 0, 0, 0, 0, 0, 0, 0, 15, 0, 0, 15, 0, 0, 0, 0, 0, 0, 0, 0}, // WrmSaturator
    {0, 0, 0, 0, 0, 0, 0, 0}, // Resonator
    {0, 0, 0, 0}, // DJFX Looper
    {0, 0, 0, 0, 15, 15}, // Chorus
    {0, 0, 0, 0}, // JUNO Chorus
    {0, 0, 0, 0, 0, 15, 15, 0, 0}, // Tremolo/Pan
    {0, 0, 0, 0, 0, 0, 0, 15, 15, 0}, // Wah
    {0, 0, 0, 0, 0, 0, 0, 0}, // Sync Delay
    {0, 15, 0, 15, 0, 0, 15, 0, 0, 15, 0, 0}, // Equalizer
    {0, 0, 0, 0, 0, 0, 0}, // Lo-fi
    {0, 0, 0, 15, 15, 0, 0}, // Ring Mod
    {0, 0, 0, 0, 0, 0, 0, 0, 15, 15, 0, 0}, // Chromatic PS
    {0, 0, 0, 0, 0, 15, 0, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, // Gt Amp Sim
    {0, 0, 0, 0, 0, 0}, // Stopper
    {0, 0, 0, 0, 0}, // Downer
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, // Slicer
    {0, 0, 0, 0, 0, 0}, // Auto Pitch
    {0, 0, 0, 0, 0}, // Compressor
    {0, 0, 0, 0, 0, 0}, // COMPRESSOR 2
    {0, 0, 0, 0, 0}, // Scatter
    {0, 0, 0, 0, 0, 0}, // 404 VinylSim
    {0, 0, 0, 0, 0}, // 303 VinylSim
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, // Zan-Zou
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, // Super Filter
    {0, 0, 0, 0, 0, 0, 0, 0}, // Hyper-Reso
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, // Ko-Da-Ma
    {0, 0, 0, 0, 0, 0, 0}, // Ha-Dou
    {0, 0, 0, 0, 0, 0, 0}, // To-Gu-Ro
    {0, 0, 0, 0, 0, 0, 0}, // Cassette Sim
    {0, 0, 0, 0, 0}, // SBF
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 15, 0}, // SX Delay
    {0, 0, 0, 0, 0, 0, 0, 0}, // Vocoder
    {0, 0, 0, 0, 0, 0}, // Harmony
    {0, 0, 0, 0, 0, 0}, // SX Reverb
    {0}, // Sub Sonic
    {0, 0, 0, 0, 0, 0, 0, 0}, // Back Spin
    {0, 0, 0, 0, 0, 0}, // Cloud Delay
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, // DJFX Delay
};

constexpr const char *kNames[49] = { "Bypass", "Filter+Drive", "TimeCtrlDly", "Isolator", "Crusher", "Phaser", "Flanger", "Overdrive", "Distortion", "Tape Echo", "Reverb", "WrmSaturator", "Resonator", "DJFX Looper", "Chorus", "JUNO Chorus", "Tremolo/Pan", "Wah", "Sync Delay", "Equalizer", "Lo-fi", "Ring Mod", "Chromatic PS", "Gt Amp Sim", "Stopper", "Downer", "Slicer", "Auto Pitch", "Compressor", "COMPRESSOR 2", "Scatter", "404 VinylSim", "303 VinylSim", "Zan-Zou", "Super Filter", "Hyper-Reso", "Ko-Da-Ma", "Ha-Dou", "To-Gu-Ro", "Cassette Sim", "SBF", "SX Delay", "Vocoder", "Harmony", "SX Reverb", "Sub Sonic", "Back Spin", "Cloud Delay", "DJFX Delay" };
constexpr int kParamCount[49] = { 0, 7, 9, 4, 3, 7, 8, 4, 4, 13, 7, 22, 8, 4, 6, 4, 9, 10, 8, 12, 7, 7, 12, 18, 6, 5, 10, 6, 5, 6, 5, 6, 5, 20, 12, 8, 11, 7, 7, 7, 5, 13, 8, 6, 6, 1, 8, 6, 11 };

} // namespace fxp
