"""Build the effect parameter map from the firmware's own tables.

    python tools/fxtable.py [BOOT_DT1_DUMP] > core/fx/fxmap.json
    python tools/fxtable.py --header > core/fx/fxparams.h

Sources (firmware 5.52, from tools/unpack.py's build/regions):
  - effect names, by effect ID:    0x8020b3d8 (pointers; 0 = Bypass)
  - parameter names, by param ID:  0x80245ee4 (627 pointers)
  - per effect, the six parameters it sends to the BMC (CTRL 1-3 first):
                                   0x802e5b40 (24-byte records by effect ID)
Addresses: an effect parameter is written to 03 hi lo aa, where
hi:lo = (effect - 1) * 5 + slot (7-bit halves) and aa = 2 * (param ID -
the effect's first param ID). The first IDs are recovered from a boot dump
of tools/fxmap.py (-o), which writes each effect's six parameters.
"""
import json, os, struct, sys
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
R = os.path.join(ROOT, 'build', 'regions')
sys.stdout.reconfigure(newline='\n', encoding='utf-8')   # LF, even on Windows
code = open(os.path.join(R, 'r_80000000_copy.bin'), 'rb').read()
data = open(os.path.join(R, 'r_80245740_decompress.bin'), 'rb').read()


def cstr(a):
    o = a - 0x80000000
    return code[o:code.find(b'\0', o)].decode('latin1')


def word(region, base, a):
    return struct.unpack_from('<i', region, a - base)[0]


fx_names = [cstr(word(code, 0x80000000, 0x8020b3d8 + 4 * i) & 0xffffffff) for i in range(49)]
p_names = [cstr(word(data, 0x80245740, 0x80245ee4 + 4 * i) & 0xffffffff) for i in range(627)]
records = {i: [word(data, 0x80245740, 0x802e5b40 + 24 * i + 4 * k) for k in range(6)] for i in range(1, 49)}

args = [a for a in sys.argv[1:] if not a.startswith('--')]
dump = args[0] if args else os.path.join(ROOT, 'core', 'fx', 'boot_dt1.txt')
sent = defaultdict(dict)       # effect -> {param offset: value} (slot 1)
for line in open(dump):
    if ' <- ' not in line:
        continue
    a, d = line.strip().split(' <- ')
    a = bytes.fromhex(a.replace(' ', ''))
    if a[0] != 3:
        continue
    block = a[1] * 128 + a[2]
    fx, slot = block // 5 + 1, block % 5
    v = 0
    for n in bytes.fromhex(d.replace(' ', '')):
        v = v * 16 + n
    sent[(fx, slot)][a[3] // 2] = v

bases = {}
for fx in range(1, 49):
    ids = sorted(x for x in records[fx] if x >= 0)
    offs = sorted(sent[(fx, 1)])
    bases[fx] = ids[0] - offs[0]
    assert [i - bases[fx] for i in ids] == offs, (fx, ids, offs)
bases[49] = 546                                      # "Mode": the system block again

out = []
for fx in range(1, 49):
    ids = list(range(bases[fx], bases[fx + 1]))
    rec = [x for x in records[fx] if x >= 0]
    out.append({
        'id': fx,
        'name': fx_names[fx],
        'ctrl': [p_names[x] for x in rec[:3]],
        'params': [{'name': p_names[i], 'addr': 2 * (i - bases[fx]),
                    'default': {str(s): sent[(fx, s)].get(i - bases[fx]) for s in range(5)
                                if sent[(fx, s)].get(i - bases[fx]) is not None} or None}
                   for i in ids],
    })
# CTRL knob ranges measured by sweeping each MFX effect's knobs
# (tools/fxmap.py; the capture is kept in core/fx/ctrl_sweep.txt).
import re
sweep = os.path.join(ROOT, 'core', 'fx', 'ctrl_sweep.txt')
if os.path.exists(sweep):
    seen = defaultdict(dict)
    for line in open(sweep):
        m = re.match(r'knob:CTRL_(\d),(\d+)\s+(.*)', line)
        if not m:
            continue
        for w in m[3].split('; '):
            mm = re.match(r'03 ([0-9a-f]{2}) ([0-9a-f]{2}) ([0-9a-f]{2}) <- (.*)', w)
            if not mm:
                continue
            block = int(mm[1], 16) * 128 + int(mm[2], 16)
            v = 0
            for n in bytes.fromhex(mm[4].replace(' ', '')):
                v = v * 16 + n
            seen[(block // 5 + 1, int(mm[3], 16))][int(m[2])] = v
    for e in out:
        for p in e['params']:
            r = seen.get((e['id'], p['addr']))
            if r and 0 in r:
                p['max'] = r[0]

if '--header' in sys.argv:
    def ident(s):
        return re.sub(r'[^A-Z0-9]+', '_', s.upper()).strip('_')
    print('// Generated by tools/fxtable.py --header (the sources of core/fx/fxmap.json).')
    print('// Parameter indices (address / 2) of each BMC effect, by effect ID.')
    print('#pragma once')
    print()
    print('namespace fxp {')
    print()
    for e in out:
        print('// %d %s (CTRL 1-3: %s)' % (e['id'], e['name'], ', '.join(e['ctrl'])))
        used = {}
        names = []
        for p in e['params']:
            n = ident(p['name'])
            used[n] = used.get(n, 0) + 1
            names.append(n if used[n] == 1 else '%s_%d' % (n, used[n]))
        print('namespace %s { enum { %s, COUNT }; }' % ('fx%02d' % e['id'], ', '.join(names)))
    # The boot dump sends only six parameters per effect; the rest keep the
    # BMC's own defaults, which we cannot see. Start the EQ-style gains
    # (0-30 around 15 = 0 dB) at 0 dB rather than -15.
    eq = {'EQ LOW', 'EQ HIGH', 'BASS', 'TREBLE', 'MID GAIN', 'MID2 GAIN', 'HIGH GAIN', 'LOW GAIN'}
    print()
    print('// Starting values of parameters the firmware may never send (by effect, index).')
    print('constexpr unsigned char kNeutral[49][32] = {')
    print('    {},')
    for e in out:
        vals = [15 if p['name'] in eq and not (e['id'] == 1) else 0 for p in e['params']]
        print('    {%s}, // %s' % (', '.join(str(v) for v in vals), e['name']))
    print('};')
    print()
    print('constexpr const char *kNames[49] = { "Bypass", %s };' % ', '.join('"%s"' % e['name'] for e in out))
    print('constexpr int kParamCount[49] = { 0, %s };' % ', '.join(str(len(e['params'])) for e in out))
    print()
    print('} // namespace fxp')
    sys.exit()

json.dump(out, sys.stdout, indent=1)
print()
